language: android
android:
  components:
    # The BuildTools version used by your project
    - build-tools-28.0.2

    # The SDK version used to compile your project
    - android-28
    
script:
  - ./gradlew assembleDebug